= Dealing with Java quircks while switching to FP style

_originally posted on the Idemia Digital Lab Poland https://www.facebook.com/idemiadigitallabpoland/[Facebook page]_

Functional programming promises easy testing and reasoning about the execution flow – without surprising exceptions, hard-to-track variables and collections mutations, nor coupling program definition with interpretation.

Thus Java constantly gains more features supporting writing code in functional style, starting with 2014's addition of lambdas and streams of collection elements.
Yet it looks like the language architects are not convinced if fully support that trend by not providing basic combinator methods (`zip`, `zipWith`, `fold`) with existing `Optional<T>` and `Stream<T>` classes, nor classes that can convey information about a failure like `Try<T>` or `Either<E, T>` which limits the possibility of writing more complicated logic without nasty mixture of good ol' `try {}` s and mutable elements.
Here we'll explore a couple of libraries that make it easier to stay with the FP side.

_All code examples are provided in https://github.com/palkakrzysiek/fp-java-playground[this github repository]._

== The basics – data classes
It's not an easy task to operate on data classes without a lot of boilerpate. Getters, builders, equals and hashcode methods can take more space than the data of interests itself. A notable library to cut out the boilerplate is https://mvnrepository.com/artifact/org.immutables/value[Immutables]. A well known, yet controversial library is https://mvnrepository.com/artifact/org.projectlombok/lombok[Lombok]. The former generates the code with concrete implementations form abstract classes, with the latter you'll end up with a different bytecode in your _*.class_ files than in your _*.java_ ones. As I don't mind it as long as IDEs and maven support provides good support, and as there are more chances you already have it in your project, I'll pick Lombok for subsequent examples.

=== How to live without setters

Here's an example of an immutable class that isn't bloated with unnecessary information (all-args constructor, builder, equals+hashCode, getters).

[source,java]
----
import lombok.Builder;
import lombok.Value;

import java.time.ZonedDateTime;
import java.util.Optional;

@Value
@Builder(toBuilder = true)
class Customer {

  @Value
  @Builder(toBuilder = true)
  static class Addrees {

    // Note that if you want to (de)serialize Optionals with Jackson you need to add jackson-datatype-jdk8 dependency and register Jdk8Module module in the Object mapper

    private Optional<String> line1;
    private Optional<String> line2;
    private Optional<String> zipCode;
    private Optional<String> city;
    private Optional<String> country;
  }

  private String name;
  private Addrees address;
  private ZonedDateTime bornOn;
  private Boolean active;
}
----

Here, the `@Value` annotation creates all the necessary methods (not including setters) to be used in immutable class. To use it in IntelliJ you must turn on annotation processors in settings.

So far so good, the problem appears when one wants to change a single filed in an object. Normally it'd require rewriting all the parameters from the old object to the constructor of the class. It's quite a tedious task and a temptation to add getters by switching `@Value` to `@Data`.

To ease the pain of "mutating" immutable objects one can add a builder with `toBuilder` argument set to `true` (unfortunately it's not a default value). This allows to summon the builder with pre-filled fields from an existing object.

As an simple example let's use the builder to solve a task of deactivating all users in a list.

[source,java]
----
  static List<Customer> deactivateCustomers(List<Customer> customers) {
    return customers
        .stream()
        .map(customer -> customer
            .toBuilder()
            .active(FALSE)
            .build())
        .collect(Collectors.toList());
  }
----

Given a such test data provider

[source,java]
----

  List<Customer> getTestConsumers() {
    return List.of(
        Customer
            .builder()
            .name("John Kovalsky")
            .address(Customer.Addrees
                .builder()
                .line1(of("Warszawska 1"))
                .line2(empty())
                .zipCode(of("00-000"))
                .city(of("Warsaw"))
                .country(of("Poland"))
                .build())
            .active(TRUE)
            .bornOn(ZonedDateTime.of(2014, 3, 18, 12, 0, 0, 0, UTC))
            .build(),
        Customer
            .builder()
            .name("Jan Kowalski")
            .address(Customer.Addrees
                .builder()
                .line1(of("Warszawska 2"))
                .line2(empty())
                .zipCode(of("00-001"))
                .city(of("Warszawa"))
                .country(of("Polska"))
                .build())
            .active(FALSE)
            .bornOn(ZonedDateTime.of(2019, 3, 18, 12, 0, 0, 0, UTC))
            .build()
    );
  }
----


[source,java]
----
  @Test
  void deactivateConsumersTest() {
    var originalList = getTestConsumers();

    var result = deactivateCustomers(originalList);

    result.forEach(customer ->
        assertThat(customer.getActive())
            .describedAs("Customer [" + customer + "] should not be active")
            .isEqualTo(FALSE)
    );

    assertThat(originalList)
        .describedAs("Customer objects in the original list are not modified")
        .containsExactly(getTestConsumers().toArray(new Customer[0]));
  }
----

Now, more complicated example. Given that we must normalize all the country values from local to English names in a collection of `Customer`s.


[source,java]
----

  // the best we can get in a language without type aliases
  @FunctionalInterface
  private interface CustomerMapper extends Function<Customer, Customer> {
  }

  private static CustomerMapper countryRenamer(String oldValue, String newValue) {
    return customer -> {
      var oldAddress = customer.getAddress();
      return customer
          .toBuilder()
          .address(oldAddress
              .toBuilder()
              .country(oldAddress
                  .getCountry()
                  // don't revert to isPresent which makes the code looks not better than if (x != null) {...}
                  // remember that Optional<A> has convenient .map(A -> B) and .flatMap(A -> Optional<B>) methods
                  .map(countryName -> countryName.replace(oldValue, newValue)))
              .build())
          .build();
    };
  }
----

No need of rewriting each field, but still some nested code, is probably the most we can get if we stick to Java. To see how replacing a single element is a nested structure can be cleaned up in other languages check the https://julien-truffaut.github.io/Monocle/optics/lens.html[Lenses concept].

For completeness here's the usage usage (and one country name for simplicity)

[source,java]
----
  static List<Customer> normalizeCountry(List<Customer> customers) {
    var oldVal = "Polska";
    var newVal = "Poland";
    var result = customers
        .stream()
        // as customer is immutable we dont have to worry about changes to the original values in the countryRenamer, whatever its implementation is...
        .map(countryRenamer(oldVal, newVal))
        .collect(Collectors.toList());
    // ... and can compare the original list to the new list
    if (log.isDebugEnabled()) log.debug("Normalized countries from {} resulting in {}", customers, result);
    return result;
  }
----

[source,java]
----
  Set<String> ALlOWED_COUNTRY_NAMES = Set.of("USA", "France", "India", "Poland");

  @Test
  void countryNamesAfterNormalizationContainOnlyAllowedValues() {
    normalizeCountry(getTestConsumers()) .forEach(customer ->
        customer.getAddress().getCountry().ifPresent(countryName ->
            assertThat(countryName)
            .describedAs("The country name of [" + customer + "] after the normalization, if present should be within allowed value set ["+ ALlOWED_COUNTRY_NAMES + "]")
            .isIn(ALlOWED_COUNTRY_NAMES)
            )
        );
  }

----

We can compare the original and new values in the log statement, as the objects from the original list couldn't be modified in the `.map(...)` stream pipeline element.

==== Side note: `Optional<T>` as a field
When you try to use `Optional<T>` as a field in IntelliJ you'll be greeted with a warning

____
Inspection info: Reports any uses of java.util.Optional<T>, java.util.OptionalDouble, java.util.OptionalInt, java.util.OptionalLong or com.google.common.base.Optional as the type for a field or a parameter. Optional was designed to provide a limited mechanism for library method return types where there needed to be a clear way to represent "no result". Using a field with type java.util.Optional is also problematic if the class needs to be Serializable, which java.util.Optional is not.
____

Don't panic. https://stackoverflow.com/a/26328555[Here's a possible source of the inspection rule] written by https://www.linkedin.com/in/briangoetz/[Brian Goetz]. Usage of `Optional` here is fine for our purpose. Libraries like https://github.com/FasterXML/jackson[Jackson] can deal with (de)serialization. With Lombok you need to use https://github.com/FasterXML/jackson-modules-java8[jackson-modules-java8].

==== Side note: developing intuition about the type bounds of generics in methods taking `Function<? super T, ? extends R>` as a parameter

// TODO

== What about the processed `Stream` elements?
A temptation to use mutable state in a `Stream<T>` comes when we need to access a previous element that has already been processed. Say we need to summarize changes in `Customer` objects for auditing purposes. First come up with a  machinery for producing a string with differences between 2 objects.

Here defined is a map of attribute names to their projectors on a customer object

[source,java]
----
  @Value
  private static class ComparableAttribute {
    private String name;
    private Function<Customer, String> getter;
  }

  private static final List<ComparableAttribute> COMPARABLE_ATTRIBUTES = List.of(
      new ComparableAttribute("name", Customer::getName),
      new ComparableAttribute("address", c -> c.getAddress().toString()),
      new ComparableAttribute("born on", c -> c.getBornOn().toString()),
      new ComparableAttribute("is active", c -> c.getActive().toString())
  );
----

Now let's try to define actual builder of a `String` with changes summary

[source,java]
----
  private static Optional<String> valueDiff(String valueName, String v1, String v2) {
    if (v1.equals(v2)) return Optional.empty();
    else return Optional.of(valueName + ": " + v1 + " -> " + v2);
  }

  static String customerDiff(Customer c1, Customer c2) {
    return COMPARABLE_ATTRIBUTES
        .stream()
        .map(attr -> valueDiff(attr.name, attr.getGetter().apply(c1), attr.getter.apply(c2)))
        .filter(Optional::isPresent)
        .map(Optional::get)
        .collect(Collectors.joining(" | "));
  }
----

(test data placed at the end of this section)

[source,java]
----
  @Test
  void customerDiffTest() {
    assertThat(Zipping.customerDiff(c1, c3)).isEqualTo("name: Johny Kovalsky -> Jan Kowalski | born on: 2014-03-18T12:00Z -> 2019-03-18T12:00Z | is active: true -> false");
  }
----

And the use it

[source,java]
----
  static List<String> compareSubsequentChangesWithAtomicRefence(List<Customer> customerStateSnapshots) {
    if (customerStateSnapshots.size() < 2) return Collections.emptyList();
    final var lastValue = new AtomicReference<>(customerStateSnapshots.get(0));
    return customerStateSnapshots
        .stream()
        .skip(1)
        .map(customer -> customerDiff(lastValue.getAndSet(customer), customer))
        .collect(Collectors.toList());
  }
----

The `lastValue` constant indicates a strong desire to use Streams but and problem of enforcing that used variables must be declared as final. `AtomicReference<Customer>` is a quick hack for changing for each loop to the _New Fancy Functional Streams™_.

It's a nasty hack, of course. All the promises of simplicity about reasoning about code is thrown away when one needs to keep track of all the places where a variable can be mutated. One can argue that it's not a big deal when the mutable state isn't leaked outside such a method, and it's valid claim. But in this case it'd be easier to just use a variable and old loops.

==== Zipping it

An easy way to compare two subsequent elements is to combine two streams -- the original one and one with the first element skipped. Unfortunately `java.util.Stream` lacks such a method. Insufficiencies of Java's standard libraries make it a high time to start using the http://www.vavr.io/[vavr] library.

I'll be addressing vavr classes with fully qualified package names (`io.vavr.*`) to avoid confusion which class in the code example belongs to standard Java, and which not. Normally you can import vavr counterparts of java classes to make the code more succinct.

Here's how once can achieve the goal with vavr's `List`


[source,java]
----
  static List<String> compareSubsequentChanges(List<Customer> customerStateSnapshots) {
    if (customerStateSnapshots.size() < 2) return Collections.emptyList();
    final var vavrList = io.vavr.collection.List.ofAll(customerStateSnapshots);
    return vavrList
        .zipWith(vavrList.drop(1), Zipping::customerDiff)
        .asJava();
  }
----

First, Java's List is changed to vavr's one. Than in the https://static.javadoc.io/io.vavr/vavr/0.9.0/io/vavr/collection/List.html#zipWith-java.lang.Iterable-java.util.function.BiFunction-[zipWith] the original collection is combined with the one without the first element using `Zipping::customerDiff` as a method taking two elements, one from each collection, and returning the result. It's worth to check other https://static.javadoc.io/io.vavr/vavr/0.9.0/io/vavr/collection/List.html#zipWith-java.lang.Iterable-java.util.function.BiFunction-[methods provided by vavr collections] which can be missing in Java's `Stream`.

Note that creating a lazy `Stream` and than `.collect` ing the result is not obligatory in vavr's collections. This allows to clean up the code logic. If one switches to vavr completely, `.asJava()` becomes unnecessary as well.

=== Generalizing with foldX

Let's now use more universal mechanism when we want to access any state that in an imperative style would be a variable(s) updated in a loop.

[source,java]
----
  @Value
  private static final class ComparisionState {
    final Customer lastVale;
    final io.vavr.collection.List<String> stateAcc;
  }

  static List<String> compareSubsequentChangesWithFoldLeft(List<Customer> customerStateSnapshots) {
    if (customerStateSnapshots.size() < 2) return Collections.emptyList();
    final var zero = new ComparisionState(customerStateSnapshots.get(0), io.vavr.collection.List.empty());
    final var vavrList = io.vavr.collection.List.ofAll(customerStateSnapshots);
    return vavrList
        .drop(1)
        .foldLeft(zero, (ComparisionState foldAcc, Customer c) ->
            new ComparisionState(c, foldAcc.stateAcc.append(customerDiff(foldAcc.lastVale, c))))
        .stateAcc
        .asJava();
  }
----

The `foldLeft` method (absent in Java's `Stream`) is generally used like

[source,java]
----
.foldLeft(defaultState, (currentState, newElement) -> newState))
----

The default element is sometimes called _zero_, sometimes _unit_. To see why think about most basic examples of associative binary operations with _neutral_ elements (such combination is called a _monoid_)

* Sum: the neutral element is 0 and the binary operation is + (hence zero)
[source,java]
----
    assertThat(io.vavr.collection.List
        .of(1, 2, 3, 4)
        .foldLeft(0, (a, b) -> a + b))
        .isEqualTo(10);
----
* Product: the neutral element is 1 and the binary operation is * (hence unit)
[source,java]
----
    assertThat(io.vavr.collection.List
        .of(1, 2, 3, 4)
        .foldLeft(1, (a, b) -> a * b))
        .isEqualTo(24);
----

I'll stick with _zero_ name, as this is what the element is called in vavr. We know that there always be zero element due to the guard code `if (customerStateSnapshots.size() < 2) return Collections.emptyList();`. It could be simplified if there were a type like `NonEmptyList` with `foldLeft` not requiring the zero element. Such addition was proposed on the https://github.com/vavr-io/vavr/issues/1244[vavr's issue tracker], but apparently wasn't sufficiently motivated and was rejected.

After reducing the list to just the state object, we access its `.stateAcc` field which is a vavr `List` and convert it to Java counterpart with `.asJava()`. Notice that `.stateAcc` is not accessed via a getter, but directly. Its intentional because ComparisionState is final, thus getter cannot be overridden and return something different in a subclass. `.stateAcc` itself is final as well, it cannot be changed without reflection. Overall, unless we want to fit in the java bean convention, there's no point of using getters layer.

=== Test data
[source,java]
----
  private Addrees address = Addrees
                .builder()
                .line1(of("Warszawska 1"))
                .line2(empty())
                .zipCode(of("00-000"))
                .city(of("Warsaw"))
                .country(of("Poland"))
                .build();

  private Customer c1 = Customer
            .builder()
            .name("Johny Kovalsky")
            .address(address)
            .active(TRUE)
            .bornOn(ZonedDateTime.of(2014, 3, 18, 12, 0, 0, 0, UTC))
            .build();

  private Customer c2 = Customer
      .builder()
      .name("John Kovalsky")
      .address(address)
      .active(TRUE)
      .bornOn(ZonedDateTime.of(2014, 3, 18, 12, 0, 0, 0, UTC))
      .build();

  private Customer c3 = Customer
            .builder()
            .name("Jan Kowalski")
            .address(address)
            .active(FALSE)
            .bornOn(ZonedDateTime.of(2019, 3, 18, 12, 0, 0, 0, UTC))
            .build();

----

== Dealing with failures
Checked exceptions don't blend with `Streams`. Runtime exceptions don't blend with predictable methods invocations. Let's start with such service

[source,java]
----
  @AllArgsConstructor
  static class CustomerService {
    private io.vavr.collection.List<Customer> customersSource;

    static class ServiceException extends Exception {
      ServiceException(String msg) {
        super(msg);
      }
    }

    Optional<Customer> getByNameOptionalThrowing(String name) throws ServiceException {
      if ("Error-prone Customer".equals(name)) throw new ServiceException("Life is life... Nananana");
      return customersSource.find(c -> c.getName().equals(name)).toJavaOptional();
    }
  }
----

And a task of getting the average age of a list of customers. First attempt

[source,java]
----
    try {
      res = names
          .stream()
          .map(name -> cs.getByNameOptionalThrowing(name))
          // further processing
          .collect(Collectors.toList());
    } catch (CustomerService.ServiceException e) {
      log.error("An error obtaining customers", e);
    }
----

And a disappointment
____
Error:(77, 52) java: unreported exception com.kpalka.fpplayground.FailableBehaviour.CustomerService.ServiceException; must be caught or declared to be thrown
Error:(80, 7) java: exception com.kpalka.fpplayground.FailableBehaviour.CustomerService.ServiceException is never thrown in body of corresponding try statement
____

`.map` won't accept something that throws a checked exception, so the second attempt

[source,java]
----
  static Integer getAvgAge(CustomerService cs, List<String> names, ZonedDateTime now) {
    // Don't do this at home
    Function<String, Optional<Customer>> aHackYouCanSometimesSpot = name -> {
      try {
        return cs.getByNameOptionalThrowing(name);
      } catch (CustomerService.ServiceException e) {
        // A service tries to inform me in the method signature that something can go wrong, but I cannot use a method that throws an exception inside `.map()`. But I REALLY want to use that fancy Stream feature... Hmm...
        throw new RuntimeException(e);
      }
    };

    // I often see similar examples used to show the possibilities of Stream<T> and method references...
    return names
        .stream()
        .map(aHackYouCanSometimesSpot) // ... and when I see such a call to service as a fragment of stream pipeline I smell something bad. Things can fail. In a nasty way. And I think such situations make some people, softly said, not very willing to incorporate the newer features of the language to their daily usage
        // the rest of processing
  }
----

Now by calling getAvgAge we aren't even informed that something can go wrong, so it's easy to forget to handle an error. The argument of easier reasoning about a program written in the functional style apparently doesn't apply here.

For a moment let's try to finish the broken implementation and then fix error handling part.

We're gonna need a class representing state that will be used in the reducing a stream of customers' age to the average value

[source,java]
----
  @AllArgsConstructor
  static class AvgPeriodCounter {
    static final AvgPeriodCounter ZERO = new AvgPeriodCounter(Period.ZERO, 0);
    final Period sum;
    final Integer elementsNumber;

    AvgPeriodCounter plus(Period period) {
      return new AvgPeriodCounter(sum.plus(period), elementsNumber + 1);
    }

    AvgPeriodCounter plus(AvgPeriodCounter avgPeriodCounter) {
      return new AvgPeriodCounter(sum.plus(avgPeriodCounter.sum), elementsNumber + avgPeriodCounter.elementsNumber);
    }

    int getAvgYear(ZonedDateTime relativeTo) {
      return Period.between(relativeTo.minus(sum).toLocalDate(), relativeTo.toLocalDate()).getYears() / elementsNumber;
    }
  }
----

And again, this time the complete implementation

[source,java]
----
  static Integer getAvgAge(CustomerService cs, List<String> names, ZonedDateTime now) {
    Function<String, Optional<Customer>> aHackYouCanSometimesSpot = name -> {
      try {
        return cs.getByNameOptionalThrowing(name);
      } catch (CustomerService.ServiceException e) {
        throw new RuntimeException(e);
      }
    };

    var toAge = periodTo(now);

    return names
        .stream()
        .map(aHackYouCanSometimesSpot)
        .filter(Optional::isPresent)
        .map(Optional::get)
        .map(Customer::getBornOn)
        .map(toAge)
        .reduce(AvgPeriodCounter.ZERO,
            (AvgPeriodCounter acc, Period p) -> acc.plus(p),
            (AvgPeriodCounter acc1, AvgPeriodCounter acc2) -> acc1.plus(acc2)
        )
        .getAvgYear(now);
  }
----

_(test data at the end of the section)_
[source,java]
----
  @Test
  void countAvgForExistingCustomers() {
    assertThat(FailableBehaviour.getAvgAge(cs, existingNames, now))
        .describedAs("Counts the avg of existing customers' age")
        .isEqualTo(avgAge);
  }

  @Test
  void countAvgThrowing() {
    assertThatThrownBy(() -> FailableBehaviour.getAvgAge(cs, List.of(errorProneCustomer), now))
        .describedAs("Method can throw an expected error, but doesn't inform that it can fail in any way. Additionally, meaningful ServiceException is wrapped very generic RuntimeException")
        .isExactlyInstanceOf(RuntimeException.class);
  }
----

It's worth noticing the (over)complicated reduce (available in Java's Stream). Compared to the `foldLeft` available in vavr, in `reduce` we have two stages. The first is the same as in `foldLeft`, the second combines the states produced by the first stage.

In the first, the new accumulated state is dependent on the previous previous value of the stream. In the second states can be combined in independently, which means they can be paralleled. It's great if you need it. If you don't you have to deal with the burden of defining additional binary operation, here `AvgPeriodCounter plus(AvgPeriodCounter avgPeriodCounter)` next to `AvgPeriodCounter plus(Period period)`. So if we already have the whole list in memory, using `foldX` seams to be a sexier solution than `reduce`.

Now its time to tame the method calls that can fail. vavr offers Try<T> and Either<E, T> classes with which you can inform about possible failre in the return type. Either is more powerful as you can put in `Left` (failure) part anything signaling the error. `Try` can be seen as

[source,java]
----
    interface Try<T> extends Either<Throwable, T> {}
----

So the errors can be only a (sub)instance of `Throwable`. Say it's good enough for now. Let's add to the `CustomerService`

[source,java]
----
    Try<Optional<Customer>> getByNameWithTry(String name) {
      return Try.of(() -> getByNameOptionalThrowing(name));
----

Notice that there's no `throws ServiceException` in the method signature, which means it can be used within `Stream`. Notice also the construct of lazy calling another method `() -> methodThatThrows()`. Without it the exception would be thrown immediately, before vavr had a chance to wrap call execution into `Try.Success` or `Try.Failure`.

Now we're ready to use the new method of the service.


[source,java]
----
  static Try<Integer> getAvgAgeWithTry(CustomerService cs, List<String> names, ZonedDateTime now) {

    var toAge = periodTo(now);

    return Try.traverse(names, cs::getByNameWithTry) // Try<Seq<Optional<Customer>>>
        .map(customers -> customers // Seq<Optional<Customer>>
            .filter(Optional::isPresent)
            .map(Optional::get)
            .map(Customer::getBornOn)
            .map(toAge)
            .foldLeft(AvgPeriodCounter.ZERO, AvgPeriodCounter::plus)
            .getAvgYear(now)
        );
  }
----

in the client code of this method you can add on the result

[source,java]
----
    result
        .onFailure(e -> log.warn("Cannot obtain customers {}", names, e))
        .onSuccess(result -> {
          if (log.isDebugEnabled()) {
            log.debug("For customers {} received the average age {}", names, result);
          }
        });
----

[source,java]
----
  @Test
  void countAvgForExistingCustomersWithTry() {
    assertThat(FailableBehaviour.getAvgAgeWithTry(cs, existingNames, now))
        .describedAs("Counts the avg of existing customers' age")
        .isEqualTo(Try.success(41));
  }

  @Test
  void countAvgForExistingCustomersWithTryWhenThereIsAServiceException() {
    var withErrorProneCustomer = io.vavr.collection.List.ofAll(existingNames).append(errorProneCustomer).asJava();
    assertThat(FailableBehaviour.getAvgAgeWithTry(cs, withErrorProneCustomer, now).getCause())
        .describedAs("Try.Failure has the cause of ServiceException")
        .isExactlyInstanceOf(FailableBehaviour.CustomerService.ServiceException.class);
  }
----

The first thing here is to use `Try.traverse` instead of mapping each name in the list like `name -> cs.getByNameWithTry(name)` With the latter we'd end up with `Stream<Try<Optional<Customer>>>` and what we're interested in is a kind of `Try<Stream<Optional<Customer>>>`, so that we have a `Stream<Optional<Customer>>` to process. The `traverse` method does the job of "flipping" a `Stream`, or actually `Seq` with `Try`.

With a simplification it can be though about as

[source,java]
----
cs.getByNameWithTry(names.get(0)).flatMap(customer0 ->
  cs.getByNameWithTry(names.get(1)).flatMap(customer1 -> /* and so on */
    cs.getByNameWithTry(names.get(N)).map(customerN -> List.of(
        customer0, customer1, /* and so on */ customerN
    ))));
----

If any of the `flatMap` s ends with `Try.Failure` (here if the `Try.of(() -> ...))` have caught an exception) the call chain is short-circuited and the end result is the first `Try.Failure`. Otherwise it's `Try.Success` with the list of processed elements.

Back to the logic. Later, the `Try<T>` behaves similarly to `Option<T>` in the way we can call `map` and `flatMap` plus some specific method like `onFailure`, `onSuccess`, `recover`, and `recoverWith`. So we're mapping a `Seq` of customers to their ages and reducing those to an average. The result can be processed further with `map` s and `flatMap` s, or we can finally call `.get()` first ensuring ourselves with `.isSuccess()` if the call succeeded.

If we're into asynchronous processing we can switch `Try` to `Future` (the vavr's one, not the Java one which has method naming inconsistent with `Stream`/`Option` part). But then be careful not to call `.get` or we'd block the execution. What can be one than is to use `.onSuccess` and `.onFailure` to complete the `Promise` of whatever framework of the library expects.


Test data used in this section
[source,java]
----
  io.vavr.collection.List<Customer> testCustomers = io.vavr.collection.List.of(
      ZonedDateTime.of(1970, 1, 1, 1, 0, 0, 0, UTC),
      ZonedDateTime.of(1990, 1, 1, 1, 0, 0, 0, UTC))
      .zipWithIndex()
      .map(bornOnIdx -> new Customer("Test John " + bornOnIdx._2,
          new Customer.Addrees(empty(), empty(), empty(), empty(), empty()),
          bornOnIdx._1,
          TRUE)
      );

  ZonedDateTime now = ZonedDateTime.of(2020, 12, 31, 1, 0, 0, 0, UTC);
  Integer avgAge = 41;
  List<String> existingNames = List.of("Test John 0", "Test John 1");
  List<String> existingAndNonexistingNames = List.of("Test John 0", "Non-existing John");

  String errorProneCustomer = "Error-prone Customer";

  FailableBehaviour.CustomerService cs = new FailableBehaviour.CustomerService(testCustomers);
----

= Summary
With some external libraries writing with functional style in Java becomes less painful. In examples above we didn't separate the program definition from its execution, which is difficult in a language without https://softwaremill.com/free-tagless-compared-how-not-to-commit-to-monad-too-early/[higher-kinded types] or a library like https://arrow-kt.io/docs/patterns/monads/[Arrow] for Kotlin. Nonetheless without mixing pre-java8 and post-lambda style (not using mutable collections, data structures, nor variables) we obtain easy to reason about code. A topic worth exploring for now http://blog.vavr.io/pattern-matching-essentials/[that's already available in vavr] and https://openjdk.java.net/jeps/8213076[may be in future added to Java] is pattern matching. It can simplify code like

[source,java]
----
    .filter(Optional::isPresent)
    .map(Optional::get)
----
with

[source,java]
----
    .collect(
        Case(Some($()), t -> t)
    )
----
and the more complicated filtering conditions and transforming logic, the more pattern matching cleans up the code.

Let me know what you're thoughts on this article and in general the topic of FP in Java because I'm curious if it's a goal worth striving for :)

